In [2]:
import torch
from torch.nn import functional as F

In [12]:
def uncertainty_score(pred):
    evidences = [F.softplus(pred)]
    print(evidences)
    alpha = dict()
    alpha[0] = evidences[0] + 1
    print(alpha)
    S = torch.sum(alpha[0], dim=1, keepdim=True)
    print(S)
    E = alpha[0] - 1
    b = E/(S.expand(E.shape))
    pred = torch.softmax(b, dim=1)
    u = 3 / S
    print(u)
    return pred

In [13]:
a = torch.randn(2,3)
b = uncertainty_score(a)
a,b

[tensor([[0.1077, 0.9426, 0.3007],
        [2.6972, 0.4521, 0.9692]])]
{0: tensor([[1.1077, 1.9426, 1.3007],
        [3.6972, 1.4521, 1.9692]])}
tensor([[4.3509],
        [7.1185]])
tensor([[0.6895],
        [0.4214]])


(tensor([[-2.1743,  0.4490, -1.0477],
         [ 2.6274, -0.5592,  0.4922]]),
 tensor([[0.3070, 0.3720, 0.3210],
         [0.3978, 0.2902, 0.3120]]))